spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/publicApi?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 3344Wanc
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9527

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: lijie-openapi

  message: dysmsapi.aliyuncs.com

#dubbo
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
    #parameters:
    #  namespace: ${spring.cloud.nacos.discovery.namespace}
  protocol:
    port: 20880
    name: dubbo

  provider:
    timeout: 3000
  #  retries: 0
  #  check: false
  # consumer:
  #  timeout: 3000
  #  retries: 0
  #  check: false
